apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web-game
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web-game
        image: aksdemoacr87.azurecr.io/web-game:72
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-game
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: web-game
